# Generated by Django 4.1.7 on 2023-05-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cat_img', models.ImageField(upload_to='category')),
            ],
        ),
    ]
