# Generated by Django 4.1.7 on 2023-05-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_category_cat_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('food_img', models.ImageField(upload_to='fooditem')),
                ('food_description', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.category')),
            ],
        ),
    ]
